### ISSUE TITLE
epic: game screen improvements

### ISSUE THREAD

**Issue by yurijmikhalevich** [move-fast-and-break-things/aibyss#46]
- [ ] add a minimap to the game screen
- [ ] zoom in on the game screen to show the players bot more closely
- [ ] ensure that the game screen occupies all available free space
- [ ] allow resizing the code editor and the game screen by dragging the separator between them
